@startuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members
package western
{
CLASS Boisson
{

}
CLASS Personnage
{
- nom:String

}
CLASS Narrateur
{

}
INTERFACE Nommable<<interface>>
{

}
CLASS Histoire4
{

}
CLASS Substantif
{
- nom:String

}
ENUM Genre<<énumération>>
{
FEMININ
MASCULIN

}
CLASS Ripou
{

}
CLASS Brigand
{
# {static} LOOK_PAR_DEFAUT:String
- look:String
- recompense:Integer 
- estLibre:boolean 

}
CLASS Cowboy
{
- gains:Integer 

}
CLASS Dame
{
- estLibre:boolean 

}
INTERFACE HorsLaLoi<<interface>>
{

}

Nommable <|... Personnage

HorsLaLoi <|... Ripou

HorsLaLoi <|... Brigand

Nommable <|-- HorsLaLoi

Personnage <|--- Narrateur

Cowboy <|--- Ripou

Personnage <|--- Brigand

Personnage <|--- Cowboy

Personnage <|--- Dame

Boisson "0..1" ---> "0..1" Substantif : substantif >

Boisson "0..1" ---> "0..1" Boisson : EAU >

Personnage "0..1" ---> "0..1" Boisson : BOISSON_PAR_DEFAUT >

Personnage "0..1" ---> "0..1" Boisson : boisson >

Substantif "0..1" ---> "0..1" Genre : genre >

Ripou "0..1" ---> "0..1" Brigand : brigand >

Brigand "*" ---> "0..1" Dame : captives >

Brigand "0..1" ---> "0..1" Cowboy : gardien >

Brigand "0..1" ---> "0..1" Boisson : boissonParDefaut >

Cowboy "*" ---> "0..1" HorsLaLoi : captures >

Cowboy "0..1" ---> "0..1" Boisson : boissonParDefaut >

Dame "0..1" ---> "0..1" Cowboy : sauveur >

Dame "0..1" ---> "0..1" HorsLaLoi : ravisseur >

Dame "0..1" ---> "0..1" Boisson : boissonParDefaut >
}
@enduml