@startuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

package western
{
CLASS Brigand
{
- recompense:Integer 
- estLibre:boolean 

}
CLASS Ripou
{

}
CLASS Substantif
{

}
CLASS Histoire4
{

}
INTERFACE Nommable<<interface>>
{

}
CLASS Dame
{
- estLibre:boolean 

}
CLASS Personnage
{

}
CLASS Cowboy
{
- gains:Integer 

}
INTERFACE HorsLaLoi<<interface>>
{

}
ENUM Genre<<énumération>>
{
+ {static} {ReadOnly} FEMININ:western.Genre 
+ {static} {ReadOnly} MASCULIN:western.Genre 

}
CLASS Boisson
{

}
CLASS Narrateur
{

}

HorsLaLoi <|... Brigand

HorsLaLoi <|... Ripou

Nommable <|... Personnage

Nommable <|... HorsLaLoi

Personnage <|--- Brigand

Cowboy <|--- Ripou

Personnage <|--- Dame

Personnage <|--- Cowboy

Personnage <|--- Narrateur

Brigand LOOK_PAR_DEFAUT : Brigand

Brigand look : Brigand

Brigand captives : Brigand

Brigand gardien : Brigand

Brigand boissonParDefaut : Brigand

Ripou brigand : Ripou

Substantif nom : Substantif

Substantif genre : Substantif

Dame sauveur : Dame

Dame ravisseur : Dame

Dame boissonParDefaut : Dame

Personnage BOISSON_PAR_DEFAUT : Personnage

Personnage nom : Personnage

Personnage boisson : Personnage

Cowboy captures : Cowboy

Cowboy boissonParDefaut : Cowboy

Boisson substantif : Boisson

Boisson EAU : Boisson
}
@enduml