@startuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

package western
{
ENUM Genre<<énumération>>
{
+ {static} {ReadOnly} FEMININ:western.Genre 
+ {static} {ReadOnly} MASCULIN:western.Genre 

}
CLASS Histoire4
{

}
CLASS Personnage
{

}
CLASS Boisson
{

}
CLASS Brigand
{
- recompense:Integer 
- estLibre:boolean 

}
CLASS Narrateur
{

}
INTERFACE HorsLaLoi<<interface>>
{

}
CLASS Dame
{
- estLibre:boolean 

}
CLASS Substantif
{

}
CLASS Ripou
{

}
INTERFACE Nommable<<interface>>
{

}
CLASS Cowboy
{
- gains:Integer 

}

Nommable <|... Personnage

HorsLaLoi <|... Brigand

Nommable <|-- HorsLaLoi

HorsLaLoi <|... Ripou

Personnage <|--- Brigand

Personnage <|--- Narrateur

Personnage <|--- Dame

Cowboy <|--- Ripou

Personnage <|--- Cowboy

Personnage --- Boisson : BOISSON_PAR_DEFAUT

Personnage --- String : nom

Personnage --- Boisson : boisson

Boisson --- Substantif : substantif

Boisson --- Boisson : EAU

Brigand --- String : LOOK_PAR_DEFAUT

Brigand --- String : look

Brigand --- Dame : captives

Brigand --- Cowboy : gardien

Brigand --- Boisson : boissonParDefaut

Dame --- Cowboy : sauveur

Dame --- HorsLaLoi : ravisseur

Dame --- Boisson : boissonParDefaut

Substantif --- String : nom

Substantif --- Genre : genre

Ripou --- Brigand : brigand

Cowboy --- HorsLaLoi : captures

Cowboy --- Boisson : boissonParDefaut
}
@enduml